apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ai-postgres
spec:
  postgresVersion: 17
  users:
    - name: longred
      databases:
        - ai-server-adv
      options: "SUPERUSER"
  config:
    parameters:
      max_connections: 3000

  instances:
    - name: pgha
      replicas: 3
      resources:
        limits:
          cpu: "4"
          memory: "16Gi"
        requests:
          cpu: "1"
          memory: "4Gi"
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 40Gi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - adtiger-3090x2
                      - adtiger-rtx-pro-6000
            - weight: 50
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: ai-postgres
                    postgres-operator.crunchydata.com/instance-set: pgha
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 40Gi

  proxy:
    pgBouncer:
      pgBouncer:
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: ai-postgres
                    postgres-operator.crunchydata.com/role: pgbouncer
